### ISSUE TITLE
Persistent storage of character data

### ISSUE THREAD

**Issue by justinwl1998** [Spikeophant/dndCharFolio#18]
All of the character data can be stored in an array or Javascript object, which can then be stored in local storage, so it would be best to add a save button at the bottom of the character creation form, which saves the character in local storage, but also adds a button below the add character button to reload that character whenever the user wants.

**Comment by Spikeophant** [comment]
@spikeophant going to pick this up instead, I have a few ideas on how to loop through all inputs and make a map based on input id to value, on save button, then on load it would be an easy map back.  I will tackle that today.

**Comment by Spikeophant** [comment]
#26  closes.  It stores, loads, and dynamically builds buttons for the character in storage.
